version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "SuaSenhaSegura123"
      MSSQL_PID: Developer  # Especifique a edição do SQL Server, se necessário
    ports:
      - "1433:1433"

